export const navigation = [
  {
    title: true,
    name: 'OPERAÇÃO',
    grupo: 'OPERACAO',
  },
  {
    name: 'Leilões',
    url: '/leilao',
    icon: 'fa fa-gavel',
    source: 'LEILOES',
    grupo: 'OPERACAO',
  },
  {
    name: 'Habilitação',
    url: '/habilitacao',
    icon: 'fa fa-check',
    source: 'HABILITACAO',
    grupo: 'OPERACAO',
  },
  {
    name: 'Vistoria',
    url: '/vistoria',
    icon: 'fa fa-search',
    source: 'VISTORIA',
    grupo: 'OPERACAO',
  },
  {
    name: 'Faturas',
    url: '/fatura',
    icon: 'fa fa-file-invoice-dollar',
    source: 'FATURA',
    grupo: 'OPERACAO',
  },
  {
    name: 'Documentos',
    url: '/gerenciador-documentos',
    icon: 'fa fa-file-alt',
    source: 'GERENCIADOR_DOC',
    grupo: 'OPERACAO',
  },
  {
    title: true,
    name: 'RELATORIOS',
    grupo: 'RELATORIOS',
  },
  {
    name: 'Dashboard',
    url: '/dashboard',
    icon: 'fa fa-chart-line',
    source: 'DASHBOARD',
    grupo: 'RELATORIOS',
  },
  {
    name: 'Mapa de Lances',
    url: '/mapa-lance',
    icon: 'fa fa-map',
    source: 'MAPA_LANCES',
    grupo: 'RELATORIOS',
  },
  {
    name: 'Histórico de Lances',
    url: '/historicolances',
    icon: 'fa fa-history',
    source: 'HISTORICO_LANCES',
    grupo: 'RELATORIOS',
  },
  {
    name: 'Lotes Consolidados',
    url: '/lancesconsolidado',
    icon: 'fa fa-file-alt',
    source: 'LANCES_CONSOLIDADOS',
    grupo: 'RELATORIOS',
  },

  {
    name: 'Arrematantes',
    url: '/arrematantes',
    icon: 'fa fa-dollar-sign',
    source: 'ARREMATANTES',
    grupo: 'RELATORIOS',
  },

  {
    name: 'Gerencial',
    url: '/gerencial',
    icon: 'fa fa-chart-line',
    source: 'GERENCIAL',
    grupo: 'RELATORIOS',
  },

  {
    title: true,
    name: 'MARKETING',
    grupo: 'MARKETING',
  },
  {
    name: 'Lista de Contatos',
    url: '/listacontatos',
    icon: 'fa fa-users',
    source: 'LISTA_CONTATOS',
    grupo: 'MARKETING',
  },
  {
    name: 'Contatos',
    url: '/contatos',
    icon: 'fa fa-user',
    source: 'CONTATOS',
    grupo: 'MARKETING',
  },
  {
    name: 'Notificações',
    url: '/notificacoes',
    icon: 'fa fa-envelope',
    source: 'NOTIFICACOES',
    grupo: 'MARKETING',
  },
  {
    name: 'Meio Notificação',
    url: '/tipomeionotificao',
    icon: 'fa fa-envelope-open',
    source: 'MEIO_NOTIFICACAO',
    grupo: 'MARKETING',
  },
  {
    name: 'Tipo Notificação',
    url: '/tiponotificacao',
    icon: 'fa fa-mail-bulk',
    source: 'TIPO_NOTIFICACAO',
    grupo: 'MARKETING',
  },
  {
    name: 'Agenda',
    url: '/agenda',
    icon: 'fa fa-book',
    source: 'AGENDA',
    grupo: 'MARKETING',
  },

  {
    name: 'Template',
    url: '/template',
    icon: 'fa fa-code',
    source: 'AGENDA',
    grupo: 'MARKETING',
  },
  {
    title: true,
    name: 'AGENDAMENTO',
    grupo: 'AGENDAMENTO',
  },
  {
    name: 'Agendamento',
    url: '/agendamento',
    icon: 'fa fa-calendar-alt',
    source: 'AGENDAMENTO',
    grupo: 'MARKETING',
  },
  {
    name: 'Configuração',
    url: '/configuracao',
    icon: 'fa fa-cog',
    source: 'CONFIG_AGENDAMENTO',
    grupo: 'MARKETING',
  },

  {
    title: true,
    name: 'GERENCIADOR SITE',
    grupo: 'GERENCIADOR SITE',
  },
  {
    name: 'Banner',
    url: '/banner',
    icon: 'fa fa-images',
    source: 'BANNER',
    grupo: 'GERENCIADOR SITE',
  },
  {
    name: 'Página Estática',
    url: '/paginaEstatica',
    icon: 'fa fa-window-maximize',
    source: 'PAGINA_ESTATICA',
    grupo: 'GERENCIADOR SITE',
  },
  {
    title: true,
    name: 'CADASTROS',
    grupo: 'CADASTROS',
  },
  {
    name: 'Permissão',
    url: '/permissao',
    icon: 'fa fa-user-cog',
    source: 'PERMISSAO',
    grupo: 'CADASTROS',
  },
  {
    name: 'Usuarios',
    url: '/usuarios',
    icon: 'fa fa-user',
    source: 'USUARIO',
    grupo: 'CADASTROS',
  },
  {
    name: 'Empresas',
    url: '/empresa',
    icon: 'fa fa-building',
    source: 'EMPRESAS',
    grupo: 'CADASTROS',
  },
  {
    name: 'Comitentes',
    url: '/comitente',
    icon: 'fa fa-university',
    source: 'COMITENTES',
    grupo: 'CADASTROS',
  },
  {
    name: 'Leiloeiros',
    url: '/leiloeiro',
    icon: 'fa fa-gavel',
    source: 'LEILOEIROS',
    grupo: 'CADASTROS',
  },
  {
    name: 'Locais',
    url: '/local',
    icon: 'fa fa-map-marker',
    source: 'LOCAIS',
    grupo: 'CADASTROS',
  },
  {
    name: 'Categorias',
    url: '/categorias',
    icon: 'fa fa-tags',
    source: 'CATEGORIAS',
    grupo: 'CADASTROS',
  },
  {
    name: 'Tipo de Documento',
    url: '/tipodocumento',
    icon: 'fa fa-file',
    source: 'TIPO_DOC',
    grupo: 'CADASTROS',
  },
  {
    name: 'Template Documento',
    url: '/documentotemplate',
    icon: 'fa fa-code',
    source: 'TEMPLATE_DOC',
    grupo: 'CADASTROS',
  },
  {
    name: 'Tipo de lote',
    url: '/tipo-lote',
    icon: 'fa fa-box',
    source: 'TIPO_LOTE',
    grupo: 'CADASTROS',
  },

  {
    name: 'Campo de lote',
    url: '/lote-campo',
    icon: 'fa fa-box',
    source: 'LOTE_CAMPO',
    grupo: 'CADASTROS',
  },

  {
    name: 'Tipo de foto',
    url: '/tipo-foto',
    icon: 'fa fa-box',
    source: 'TIPO_FOTO',
    grupo: 'CADASTROS',
  },

  {
    title: true,
    name: 'JUDICIAL',
    grupo: 'JUDICIAL',
  },

  {
    name: 'Juizo',
    url: '/juizo',
    icon: 'fa fa-user',
    source: 'JUIZO',
    grupo: 'JUDICIAL',
  },

  {
    name: 'Vara',
    url: '/vara',
    icon: 'fa fa-user',
    source: 'VARA',
    grupo: 'JUDICIAL',
  },

  {
    name: 'Juiz',
    url: '/juiz',
    icon: 'fa fa-user',
    source: 'JUIZ',
    grupo: 'JUDICIAL',
  },

  {
    name: 'Escrivao',
    url: '/escrivao',
    icon: 'fa fa-user',
    source: 'ESCRIVAO',
    grupo: 'JUDICIAL',
  },

  {
    name: 'Advogado',
    url: '/advogado',
    icon: 'fa fa-user',
    source: 'ADVOGADO',
    grupo: 'JUDICIAL',
  },

  {
    name: 'Reu',
    url: '/reu',
    icon: 'fa fa-user',
    source: 'ATOR_PROCESSO',
    grupo: 'JUDICIAL',
  },

  {
    name: 'Autor',
    url: '/autor',
    icon: 'fa fa-user',
    source: 'ATOR_PROCESSO',
    grupo: 'JUDICIAL',
  },

  {
    name: 'Parte',
    url: '/parte',
    icon: 'fa fa-user',
    source: 'ATOR_PROCESSO',
    grupo: 'JUDICIAL',
  },

  {
    name: 'Credor',
    url: '/credor',
    icon: 'fa fa-user',
    source: 'ATOR_PROCESSO',
    grupo: 'JUDICIAL',
  },

  {
    name: 'Fiel Depositario',
    url: '/fiel-depositario',
    icon: 'fa fa-user',
    source: 'ATOR_PROCESSO',
    grupo: 'JUDICIAL',
  },
];
